apiVersion: v1
kind: Service
metadata:
  name: api-gateway-load-balancer
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer