server:
  port: 8000



spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://34.80.4.224:3306/tdf_poc?autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: c7jDFzEbhy5qjOhx
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      showSql: true
      hibernate:
        ddlAuto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect



zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ignoredServices: '*'
  retryable: true
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
    authentication-service:
      serviceId: authentication-service
      path: /authentication-service/**
      stripPrefix: false



ribbon:
  eureka:
    enabled: false



authentication-service:
  ribbon:
    listOfServers: http://authentication-tcp-service:8001



eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-server-tcp-service:9000/eureka/



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
        timeout:
          enabled: false



security:
  jwt:
    expiration: 3600000*24
    secret: RbMCipPYzULnntg2NCgs1bcKukzCezuK