apiVersion: v1
kind: Service
metadata:
  name: discovery-server-load-balancer
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer