version: "3.8"

services:
  discovery-server:
    build: ./discovery-server
    image: discovery-server
    container_name: discovery-server
    ports:
      - "9000:9000"
    networks:
      - server

  api-gateway:
    build: ./api-gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    networks:
      - server
    depends_on:
      - discovery-server

  authentication-service:
    build: ./authentication-service
    image: authentication-service
    container_name: authentication-service
    ports:
      - "8001:8001"
    networks:
      - server
    depends_on:
      - discovery-server
      - api-gateway

networks:
  server:
