#server properties - port
server:
  port: 8888


#spring properties - name, db connection
spring:
  application:
    name: config-server
  profiles:
    active: native
#  datasource:
#    url: jdbc:mysql://localhost:3306/cms?autoReconnect=true&serverTimezone=UTC&useSSL=false
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#    jpa:
#      showSql: true
#      hibernate:
#        ddlAuto: update
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect