#spring properties - name, db connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms?autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


#eureka properties - eureka admin, host
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/


#authority initializer properties
default:
  admin:
    username: Gio
    email: gio@gmail.com
    password: 123


#jwt unique ID - should be stored in secured external server in future
security:
  jwt:
    expiration: 3600000*24
    secret: RbMCipPYzULnntg2NCgs1bcKukzCezuK